// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: proto/task/task.proto

package task

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TaskClient is the client API for Task service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TaskClient interface {
	GetAllTaskCases(ctx context.Context, in *CommonRequest, opts ...grpc.CallOption) (*GetAllTaskCasesReply, error)
	RunSingleTaskCase(ctx context.Context, in *RunTaskRequest, opts ...grpc.CallOption) (*RunTaskReply, error)
}

type taskClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskClient(cc grpc.ClientConnInterface) TaskClient {
	return &taskClient{cc}
}

func (c *taskClient) GetAllTaskCases(ctx context.Context, in *CommonRequest, opts ...grpc.CallOption) (*GetAllTaskCasesReply, error) {
	out := new(GetAllTaskCasesReply)
	err := c.cc.Invoke(ctx, "/api.task.Task/GetAllTaskCases", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskClient) RunSingleTaskCase(ctx context.Context, in *RunTaskRequest, opts ...grpc.CallOption) (*RunTaskReply, error) {
	out := new(RunTaskReply)
	err := c.cc.Invoke(ctx, "/api.task.Task/RunSingleTaskCase", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskServer is the server API for Task service.
// All implementations must embed UnimplementedTaskServer
// for forward compatibility
type TaskServer interface {
	GetAllTaskCases(context.Context, *CommonRequest) (*GetAllTaskCasesReply, error)
	RunSingleTaskCase(context.Context, *RunTaskRequest) (*RunTaskReply, error)
	mustEmbedUnimplementedTaskServer()
}

// UnimplementedTaskServer must be embedded to have forward compatible implementations.
type UnimplementedTaskServer struct {
}

func (UnimplementedTaskServer) GetAllTaskCases(context.Context, *CommonRequest) (*GetAllTaskCasesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllTaskCases not implemented")
}
func (UnimplementedTaskServer) RunSingleTaskCase(context.Context, *RunTaskRequest) (*RunTaskReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunSingleTaskCase not implemented")
}
func (UnimplementedTaskServer) mustEmbedUnimplementedTaskServer() {}

// UnsafeTaskServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskServer will
// result in compilation errors.
type UnsafeTaskServer interface {
	mustEmbedUnimplementedTaskServer()
}

func RegisterTaskServer(s grpc.ServiceRegistrar, srv TaskServer) {
	s.RegisterService(&Task_ServiceDesc, srv)
}

func _Task_GetAllTaskCases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServer).GetAllTaskCases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.task.Task/GetAllTaskCases",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServer).GetAllTaskCases(ctx, req.(*CommonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Task_RunSingleTaskCase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServer).RunSingleTaskCase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.task.Task/RunSingleTaskCase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServer).RunSingleTaskCase(ctx, req.(*RunTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Task_ServiceDesc is the grpc.ServiceDesc for Task service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Task_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.task.Task",
	HandlerType: (*TaskServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllTaskCases",
			Handler:    _Task_GetAllTaskCases_Handler,
		},
		{
			MethodName: "RunSingleTaskCase",
			Handler:    _Task_RunSingleTaskCase_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/task/task.proto",
}
