// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: api/task/task.proto

package task

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TaskClient is the client API for Task service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TaskClient interface {
	GetAllHttpTaskCases(ctx context.Context, in *CommonRequest, opts ...grpc.CallOption) (*GetAllHttpTaskCasesReply, error)
	RunHttpTask(ctx context.Context, in *RunHttpTaskRequest, opts ...grpc.CallOption) (*RunHttpTaskReply, error)
}

type taskClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskClient(cc grpc.ClientConnInterface) TaskClient {
	return &taskClient{cc}
}

func (c *taskClient) GetAllHttpTaskCases(ctx context.Context, in *CommonRequest, opts ...grpc.CallOption) (*GetAllHttpTaskCasesReply, error) {
	out := new(GetAllHttpTaskCasesReply)
	err := c.cc.Invoke(ctx, "/api.task.Task/GetAllHttpTaskCases", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskClient) RunHttpTask(ctx context.Context, in *RunHttpTaskRequest, opts ...grpc.CallOption) (*RunHttpTaskReply, error) {
	out := new(RunHttpTaskReply)
	err := c.cc.Invoke(ctx, "/api.task.Task/RunHttpTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskServer is the server API for Task service.
// All implementations must embed UnimplementedTaskServer
// for forward compatibility
type TaskServer interface {
	GetAllHttpTaskCases(context.Context, *CommonRequest) (*GetAllHttpTaskCasesReply, error)
	RunHttpTask(context.Context, *RunHttpTaskRequest) (*RunHttpTaskReply, error)
	mustEmbedUnimplementedTaskServer()
}

// UnimplementedTaskServer must be embedded to have forward compatible implementations.
type UnimplementedTaskServer struct {
}

func (UnimplementedTaskServer) GetAllHttpTaskCases(context.Context, *CommonRequest) (*GetAllHttpTaskCasesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllHttpTaskCases not implemented")
}
func (UnimplementedTaskServer) RunHttpTask(context.Context, *RunHttpTaskRequest) (*RunHttpTaskReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunHttpTask not implemented")
}
func (UnimplementedTaskServer) mustEmbedUnimplementedTaskServer() {}

// UnsafeTaskServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskServer will
// result in compilation errors.
type UnsafeTaskServer interface {
	mustEmbedUnimplementedTaskServer()
}

func RegisterTaskServer(s grpc.ServiceRegistrar, srv TaskServer) {
	s.RegisterService(&Task_ServiceDesc, srv)
}

func _Task_GetAllHttpTaskCases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServer).GetAllHttpTaskCases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.task.Task/GetAllHttpTaskCases",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServer).GetAllHttpTaskCases(ctx, req.(*CommonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Task_RunHttpTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunHttpTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServer).RunHttpTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.task.Task/RunHttpTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServer).RunHttpTask(ctx, req.(*RunHttpTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Task_ServiceDesc is the grpc.ServiceDesc for Task service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Task_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.task.Task",
	HandlerType: (*TaskServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllHttpTaskCases",
			Handler:    _Task_GetAllHttpTaskCases_Handler,
		},
		{
			MethodName: "RunHttpTask",
			Handler:    _Task_RunHttpTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/task/task.proto",
}
